### ISSUE TITLE
Display stops but game sim continues

### ISSUE THREAD

**Issue by AJFaraday** [AJFaraday/lane-sim#1]
At some points, seemingly at random, the gosu window disappears, but the program continues to run.

Skipping forwards in levels (closing a gosu window and initialising a new one) seems to speed this up.

Reproduction:

* `ruby campaign.rb`
* press p twice (to skip forwards)
* press up to start the sim
* wait a few seconds until window vanishes
* (observe that log messages continue to appear)

Found on KDE linux with gosu version 0.9.2

**Comment by jlnr** [comment]
Can't reproduce the issue because Ruby 2.1 chokes on `config.rb` - apparently because it uses the name `Config` internally for a deprecated module. I guess I'd need a newer version of Ruby? Anyway, the Gosu update should fix it :)

**Comment by AJFaraday** [comment]
Thanks a lot for having a look at this. I'll check on a newer version of gosu soon.

Could you log the config error message as another issue for me, please? I should get that sorted.

**Comment by AJFaraday** [comment]
This issue fixed by a gosu update (and correct source declaration) in commit b1ccf8fa243540e7adc291c384bb8f9da220fdcf

**Comment by AJFaraday** [comment]
(Never mind, I've found and fixed the config classes conflict issue)

**Comment by jlnr** [comment]
:+1: :)
